import dashboardIcon from "../public/dashboard.svg";
import requestIcon from "../public/timer.svg";
import kycIcon from "../public/search-status.svg";
import reportsIcon from "../public/mobile-programming.svg";
import tasksIcon from "../public/task.svg";
import auditIcon from "../public/link.svg";
import customersIcon from "../public/user.svg";
import usersIcon from "../public/security-user.svg";
import settingsIcon from "../public/setting-2.svg";
import administrationIcon from "../public/security.svg";

export const dashboard = dashboardIcon;
export const request = requestIcon;
export const kyc = kycIcon;
export const reports = reportsIcon;
export const tasks = tasksIcon;
export const audit = auditIcon;
export const customers = customersIcon;
export const users = usersIcon;
export const settings = settingsIcon;
export const administration = administrationIcon;
